### ISSUE TITLE
Subdocument not populating until child is changed...

### ISSUE THREAD

**Issue by kwhitley** [pgherveou/mongoosefiller#1]
Hey man, awesome concept and could really help solve the natural headache of NoSQL solutions!

I'm trying to integrate this with my project, and the example collections are similar to the following:

``` js
var GearSchema = new mongoose.Schema({
  name: { type: String }
});

var Gear = mongoose.model('Gear', GearSchema);

var BrandSchema = new mongoose.Schema({
  name: { type: String }
});

var Brand = mongoose.model('Brand', BrandSchema);
```

...

Now assuming I have a couple brands in the brands collection like follows:

``` js
[{ name: 'Canon', _id: 1 }, { name: 'Nikon', _id: 2 }]
```

If I create a new Gear like so:

``` js
var gear = new Gear({ name: '5D Mark II', brand: { _id: 1 }});

gear.save();
```

...the gear will simply have brand populated with the _id as I passed it in, like this:

``` js
{ name: '5D Mark II', brand: { _id: 1 }}
```

If I then modify the associated brand/child item (like changing its name), the gear item finally gets populated correctly.

Am I missing something?

Thanks!

**Comment by pgherveou** [comment]
Hey @kwhitley that should work just fine, let me have a look!

**Comment by pgherveou** [comment]
Try this out that should work

``` js
var mongoose = require('mongoose'),
    filler = require('mongoosefiller');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/mongoosefiller-test', function (err) {
  if (err) console.error(err);
});

var GearSchema = new mongoose.Schema({
  name: {type: String},
  brand: {_id: Number}
});

var BrandSchema = new mongoose.Schema({
  _id: {type: Number},
  name: { type: String }
});

var Gear = mongoose.model('Gear', GearSchema);
var Brand = mongoose.model('Brand', BrandSchema);

GearSchema.plugin(filler, {
  path: 'brand',
  ref : 'Brand',
  dest: 'Gear'
});

Brand.create([{ name: 'Canon', _id: 1 }, { name: 'Nikon', _id: 2 }], function (err) {
  if (err) console.error(err);
  var gear = new Gear({ name: '5D Mark II', brand: { _id: 1 }});
  gear.save(function () {
    console.log('results:', arguments);
  });
});
```

this is the output I have

```
Mongoose: brands.insert({ __v: 0, _id: 1, name: 'Canon' }) {}
Mongoose: brands.insert({ __v: 0, _id: 2, name: 'Nikon' }) {}
Mongoose: brands.findOne({ _id: 1 }) { fields: { __v: 1, name: 1, _id: 1 }, safe: undefined }
Mongoose: gears.insert({ __v: 0, brand: { __v: 0, name: 'Canon', _id: 1 }, _id: ObjectId("5267274a265280b20b000001"), name: '5D Mark II' }) {}
results: { '0': null,
  '1':
   { __v: 0,
     name: '5D Mark II',
     _id: 5267274a265280b20b000001,
     brand: { __v: 0, name: 'Canon', _id: 1 } },
  '2': 1 }

```

Let me know if something is not clear, and don't hesitate to make a pull request to clarify the doc

**Comment by kwhitley** [comment]
Thanks for the quick response... should have clarified, the `_id: 1` was just for a shorthand for an ObjectID...

So each collection would only have name defined, and Gear would have a ref to Brand.

I'll check some more sandboxed cases and see if I can get it to work in an isolated case.  Only diff I can see offhand is you manually defined an `_id: Number` on Brand...

**Comment by kwhitley** [comment]
Must be on my end somewhere... I was able to CURL it and it worked like a champ.  Thanks for the help and keep up the good work @pgherveou!
